=== mainvec/mvep/resources/schemas/wop_service.schema_latest_draft.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://pub.workoak.com/schemas/2021-10/wop_service.schema.json#",
  "title": "WO Service Definition Schema",
  "description": "WO Service config schema",
  "type": "object",
  "required": [
    "$id",
    "name",
    "namespace"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "$id": {
      "type": "string"
    },
    "name": {
      "description": "The unique name for the WOP service",
      "type": "string",
      "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
    },
    "namespace": {
      "description": "The namespace for the WOP service",
      "type": "string",
      "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
    },
    "base": {
      "type": "string"
    },
    "gen_options": {
      "description": "Generation Options",
      "type": "object",
      "patternProperties": {
        "^[A-Za-z][a-zA-Z0-9_]*$": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "title": {
      "description": "The title the WOP service",
      "type": "string"
    },
    "description": {
      "description": "The description the WOP service",
      "type": "string"
    },
    "entities": {
      "description": "Data Entities",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the entity",
            "type": "string",
            "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
          }
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },

    "commands": {
      "type": "object",
      "description": "Commands",
      "patternProperties": {
        "^[A-Za-z][a-zA-Z0-9_]*$": {
          "type": "object",
          "$ref": "#/definitions/commandDef"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "recordsDefs": {
      "description": "Record definitons Object",
      "$ref": "#/definitions/recordsDefs"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "commandDef": {
      "type": "object",
      "properties": {
        "title": {
          "description": "Name of the command",
          "type": "string"
        },
        "alias": {
          "type": "string",
          "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
        },
        "state_type": {
          "description": "The type of the command. Stateless/Stateful",
          "type": "string",
          "enum": [
            "stateless",
            "stateful",
            "cluster"
          ]
        },
        "fields": {
          "type": "object",
          "description": " fields ",
          "$ref": "#/definitions/fieldsGroupDef"
        },
        "resultFields": {
          "type": "object",
          "description": " results fields ",
          "$ref": "#/definitions/fieldsGroupDef"
        }
      },
      "additionalProperties": false,
      "defaultSnippets": [
        {
          "label": "New WO Command",
          "description": "Creates a New WO Command template",
          "body": {
            "title": "$1",
            "fields": {}
          }
        }
      ]
    },
    "payloadDef": {
      "type": "object",
      "description": "payload def",
      "oneOf": [
        {
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "string",
                "boolean",
                "int32",
                "int64",
                "float",
                "double",
                "bytes",
                "uint32",
                "sint32",
                "timestamp",
                "duration"
              ]
            }
          },
          "required": [
            "type"
          ]
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "record"
              ]
            },
            "recordDefName": {
              "type": "string",
              "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
            }
          },
          "required": [
            "type",
            "recordDefName"
          ]
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "recRef"
              ]
            },
            "$ref": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "$ref"
          ]
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "recDef"
              ]
            },
            "recordDef": {
              "type": "object",
              "description": " results fields ",
              "$ref": "#/definitions/recordDef"
            }
          },
          "required": [
            "type",
            "recordDef"
          ]
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "map"
              ]
            },
            "valueType": {
              "type": "string",
              "enum": [
                "string",
                "boolean",
                "int16",
                "int32",
                "bytes"
              ],
              "default": "string"
            }
          },
          "required": [
            "type",
            "valueType"
          ]
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "oneOf"
              ]
            },
            "fields": {
              "type": "object",
              "description": " oneOf fields defs",
              "$ref": "#/definitions/fieldsGroupDef"
            }
          },
          "required": [
            "type",
            "fields"
          ]
        }
      ]
    },
    "fieldDef": {
      "type": "object",
      "allOf": [
        {
          "type": "object",
          "required": [
            "fnum"
          ],
          "properties": {
            "alias": {
              "type": "string",
              "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
            },
            "fnum": {
              "type": "integer"
            },
            "repeated": {
              "type": "boolean",
              "default": false
            },
            "tags": {
              "description": "Field Tags",
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
              },
              "minItems": 1,
              "uniqueItems": true
            }
          }
        },
        {
          "type": "object",
          "$ref": "#/definitions/payloadDef"
        }
      ]
    },
    "fieldsGroupDef": {
      "type": "object",
      "description": " fields group definition",
      "patternProperties": {
        "^[A-Za-z][a-zA-Z0-9_]*$": {
          "type": "object",
          "$ref": "#/definitions/fieldDef"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "recordDef": {
      "type": "object",
      "properties": {
        "name": {
          "description": "name of the record definiton",
          "type": "string",
          "pattern": "^[A-Za-z][a-zA-Z0-9_]*$"
        },
        "title": {
          "description": "Name of the record definiton",
          "type": "string"
        },
        "fields": {
          "type": "object",
          "description": " Fields defintions",
          "$ref": "#/definitions/fieldsGroupDef"
        }
      },
      "required": [
        "name"
      ]
    },
    "recordsDefs": {
      "type": "object",
      "description": " record definitions definition",
      "patternProperties": {
        "^[A-Za-z][a-zA-Z0-9_]*$": {
          "type": "object",
          "$ref": "#/definitions/recordDef"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    }
  }
}

=== mainvec/mvep/mvgen/testold/valid_wo_service_01.json
{
	"$schema": "../resources/schemas/wop_service.schema_latest_draft.json",
	"$id": "https://mainvec.com#",
	"name": "wodb2",
	"namespace": "wo",
	"title": "WO DB",
	"base": "github.com/mainvec/wo/mvep/wopdb",
	"description": "Core WO DB service providing DB as a service",
	"gen_options": {
		"go_package": "github.com/mainvec/wo/mvep/wopdb/wopdb2api"
	},
	"recordsDefs": {
		"WODbParams": {
			"name": "WODbParams",
			"fields": {
				"dbname": {
					"fnum": 1,
					"type": "string"
				},
				"authtoken": {
					"fnum": 2,
					"type": "string"
				},
				"params": {
					"fnum": 10,
					"type": "map",
					"valueType": "string"
				}
			}
		},
		"FieldDesc": {
			"name": "FieldDesc",
			"fields": {
				"name": {
					"fnum": 1,
					"type": "string"
				},
				"typeOid": {
					"fnum": 2,
					"type": "uint32"
				},
				"typeSize": {
					"fnum": 3,
					"type": "sint32"
				},
				"typeModifier": {
					"fnum": 4,
					"type": "sint32"
				},
				"format": {
					"fnum": 5,
					"type": "int32"
				},
				"tableOid": {
					"fnum": 6,
					"type": "uint32"
				},
				"posInTable": {
					"fnum": 7,
					"type": "uint32"
				}
			}
		},
		"RowDesc": {
			"name": "RowDesc",
			"fields": {
				"fields": {
					"fnum": 1,
					"type": "record",
					"recordDefName": "FieldDesc",
					"repeated": true
				}
			}
		},
		"DataValue": {
			"name": "DataValue",
			"fields": {
				"value": {
					"fnum": -1,
					"type": "oneOf",
					"fields": {
						"stringV": {
							"type": "string",
							"fnum": 1
						},
						"boolV": {
							"type": "boolean",
							"fnum": 2
						},
						"intV": {
							"type": "int32",
							"fnum": 3
						},
						"longV": {
							"type": "int64",
							"fnum": 4
						},
						"floatV": {
							"type": "float",
							"fnum": 5
						},
						"doubleV": {
							"type": "double",
							"fnum": 6
						},
						"bytesV": {
							"type": "bytes",
							"fnum": 7
						},
						"timeStampV": {
							"type": "timestamp",
							"fnum": 8
						},
						"durationV": {
							"type": "duration",
							"fnum": 9
						}
					}
				}
			}
		},
		"DataRow": {
			"name": "DataRow",
			"fields": {
				"values": {
					"fnum": 1,
					"type": "record",
					"recordDefName": "DataValue",
					"repeated": true
				}
			}
		},
		"DataRows": {
			"name": "DataRows",
			"fields": {
				"rowDesc": {
					"fnum": 1,
					"type": "record",
					"recordDefName": "RowDesc"
				},
				"rows": {
					"fnum": 2,
					"type": "record",
					"recordDefName": "DataRow",
					"repeated": true
				}
			}
		}
	},
	"commands": {
		"WODbDqlCmd": {
			"title": "WODB DQL Cmd. Only query commands, e.g. SELECT statements",
			"state_type": "cluster",
			"fields": {
				"dql": {
					"fnum": 1,
					"type": "string",
					"repeated": false
				},
				"DBParam": {
					"fnum": 2,
					"type": "recRef",
					"$ref": "#/recordsDefs/WODbParams"
				}
			},
			"resultFields": {
				"rows": {
					"fnum": 1,
					"type": "recRef",
					"$ref": "#/recordsDefs/DataRows"
				}
			}
		},
		"WODbDmlCmd": {
			"title": "WODB DML Cmd. Data Manipulation Stmts, e.g. INSERT, UPDATE, DELETE statements",
			"state_type": "cluster",
			"fields": {
				"dml": {
					"fnum": 1,
					"type": "string",
					"repeated": false
				},
				"DBParam": {
					"fnum": 2,
					"type": "record",
					"recordDefName": "WODbParams"
				}
			}
		}
	}
}
